# Generated by Django 4.2.28 on 2026-03-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The date this insight was generated for", unique=True
                    ),
                ),
                (
                    "insight_text",
                    models.TextField(help_text="The AI-generated insight"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
