# Generated by Django 4.2.28 on 2026-07-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dailyinsight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyInsight',
        ),
        migrations.AddField(
            model_name='material',
            name='site_a_material_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='site_a_request_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='sync_status',
            field=models.CharField(choices=[('not_synced', 'Not Synced'), ('synced', 'Synced'), ('sync_failed', 'Sync Failed')], default='not_synced', max_length=20),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
