"""
Django settings for stockpad_backend project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").strip().lower() not in ("false", "0", "no")

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key_env = os.environ.get("DJANGO_SECRET_KEY")
if not _secret_key_env:
    if DEBUG:
        # Insecure fallback — ONLY acceptable for local development
        _secret_key_env = "django-insecure-6fqhjcz1*=p24m2ux(7z_dy=_u*m-rz(qrw41bw4q&+aim*5be"
    else:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable must be set in production.")
SECRET_KEY = _secret_key_env

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_filters",
    "api",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "stockpad_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "stockpad_backend.wsgi.application"


from django.core.exceptions import ImproperlyConfigured

db_password = os.environ.get("DB_PASSWORD")
if not db_password:
    if DEBUG:
        db_password = "postgres"
    else:
        raise ImproperlyConfigured("DB_PASSWORD environment variable is missing for production.")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "stockpad_db",        # <-- Your PostgreSQL database name
        "USER": "postgres",           # <-- Your PostgreSQL username
        "PASSWORD": db_password,
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# AUTH_USER_MODEL
AUTH_USER_MODEL = "api.User"

# REST Framework Settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# Simple JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Authentication Backends
AUTHENTICATION_BACKENDS = (
    'api.authentication_backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'stockpad.eg@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  # set via environment variable
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'stockpad.eg@gmail.com')

# Google OAuth Credentials
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')


# Website 1 (StockPad) Integration Settings
SITE_A_BASE_URL = os.environ.get("SITE_A_BASE_URL", "https://stockpad-backend-production.up.railway.app")
SITE_A_API_KEY = os.environ.get("SITE_A_API_KEY")           # sent as X-Site-B-API-Key on outbound calls
SITE_A_WEBHOOK_SECRET = os.environ.get("SITE_A_WEBHOOK_SECRET")  # used to verify X-Site-A-Signature on inbound webhooks
SITE_B_PUBLIC_WEBHOOK_URL = os.environ.get("SITE_B_PUBLIC_WEBHOOK_URL")  # e.g. https://<this-domain>/api/webhooks/material-status/

# Startup validation check for production settings
if not DEBUG:
    missing_vars = []
    if not SITE_A_API_KEY:
        missing_vars.append("SITE_A_API_KEY")
    if not SITE_A_WEBHOOK_SECRET:
        missing_vars.append("SITE_A_WEBHOOK_SECRET")
    if not SITE_B_PUBLIC_WEBHOOK_URL:
        missing_vars.append("SITE_B_PUBLIC_WEBHOOK_URL")
    
    if missing_vars:
        raise ImproperlyConfigured(
            f"Production integration settings missing: {', '.join(missing_vars)}. "
            "Please configure these environment variables."
        )